### ISSUE TITLE
Update spec for getDictInfos when subdictionary does not exist to not return an error

### ISSUE THREAD

**Issue by bblodfon** [vsm/vsm-dictionary#13]
Generally I have implemented in all vsm-dictionaries **strict-error** handling: lannching multiple queries in the respective server API, one of them goes wrong, send proper error message back (see also issue #11 )

When at least one non-proper/non-existent `options.filter.id` is given in `getDictInfos`, the server API returns an error.
For example, PubDictionaries and BioPortal servers return a JSON object with a message like `Unknown ontology/dictionary`.
We agreed at some point that these kind of errors should be ignored, e.g. see implemention in [BioPortal vsm-dictionary](https://github.com/UniBioDicts/vsm-dictionary-bioportal/blob/master/src/DictionaryBioPortal.js#L96) and [vsm-pubdictionaries](https://github.com/UniBioDicts/vsm-pubdictionaries/blob/master/src/PubDictionaries.js#L99), but this is not mentioned in the spec currently (or maybe I ddin't look hard enough?)

Please updatre spec accordingly, because even me, after creating all these dictionaries, I almost forgot to do it for a new one (had the BioPortal code to guide me through it of course :))

**Comment by stcruy** [comment]
What you describe is already specified, and at the expected place in the text:
see "Subclass GET-type Functionality" –> `getDictInfos()` –> `cb` –> `err` –> "Note"

Unless I'm missing something or if smth was unclear, I'm closing this issue.

**Comment by bblodfon** [comment]
Oh, hadn't seen it. Oh well, it's good to have it also here to remember. The text says: 
"no error occurs if no dictInfo was found for some `id` in `filter`;" => I read it as a possible empty result from the server API for a `dictInfo` but it also implies an error object (which is what happens most of the times when calling a server API with a non-existent ontology/dictionary name)

**Comment by stcruy** [comment]
Alright, I reformulated and extended it a bit now.
There was room to be more explicit, indeed.
Thanks!
